#include "src/components/feature_engagement/public/feature_constants.cc"


namespace feature_engagement {

#if BUILDFLAG(IS_ANDROID)

BASE_FEATURE(kIPHBatterySaverModeFeature,
             "IPH_BatterySaverMode",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHCompanionSidePanelFeature,
             "IPH_CompanionSidePanel",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHCompanionSidePanelRegionSearchFeature,
             "IPH_CompanionSidePanelRegionSearch",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHComposeNewBadgeFeature,
             "IPH_ComposeNewBadgeFeature",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHDesktopSharedHighlightingFeature,
             "IPH_DesktopSharedHighlighting",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHDesktopTabGroupsNewGroupFeature,
             "IPH_DesktopTabGroupsNewGroup",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHDesktopCustomizeChromeFeature,
             "IPH_DesktopCustomizeChrome",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHDesktopCustomizeChromeRefreshFeature,
             "IPH_DesktopCustomizeChromeRefresh",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHDesktopNewTabPageModulesCustomizeFeature,
             "IPH_DesktopNewTabPageModulesCustomize",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHDownloadToolbarButtonFeature,
             "IPH_DownloadToolbarButton",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHExtensionsMenuFeature,
             "IPH_ExtensionsMenu",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHExtensionsRequestAccessButtonFeature,
             "IPH_ExtensionsRequestAccessButton",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHFocusHelpBubbleScreenReaderPromoFeature,
             "IPH_FocusHelpBubbleScreenReaderPromo",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHGMCCastStartStopFeature,
             "IPH_GMCCastStartStop",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHGMCLocalMediaCastingFeature,
             "IPH_GMCLocalMediaCasting",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHHighEfficiencyModeFeature,
             "IPH_HighEfficiencyMode",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHLiveCaptionFeature,
             "IPH_LiveCaption",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHTabAudioMutingFeature,
             "IPH_TabAudioMuting",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPasswordsAccountStorageFeature,
             "IPH_PasswordsAccountStorage",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPasswordsManagementBubbleAfterSaveFeature,
             "IPH_PasswordsManagementBubbleAfterSave",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPasswordsManagementBubbleDuringSigninFeature,
             "IPH_PasswordsManagementBubbleDuringSignin",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPasswordsWebAppProfileSwitchFeature,
             "IPH_PasswordsWebAppProfileSwitch",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPasswordManagerShortcutFeature,
             "IPH_PasswordManagerShortcut",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPasswordSharingFeature,
             "IPH_PasswordSharingFeature",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPowerBookmarksSidePanelFeature,
             "IPH_PowerBookmarksSidePanel",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPriceInsightsPageActionIconLabelFeature,
             "IPH_PriceInsightsPageActionIconLabelFeature",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPriceTrackingChipFeature,
             "IPH_PriceTrackingChipFeature",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPriceTrackingEmailConsentFeature,
             "IPH_PriceTrackingEmailConsentFeature",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPriceTrackingPageActionIconLabelFeature,
             "IPH_PriceTrackingPageActionIconLabelFeature",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHReadingListDiscoveryFeature,
             "IPH_ReadingListDiscovery",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHReadingListEntryPointFeature,
             "IPH_ReadingListEntryPoint",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHReadingListInSidePanelFeature,
             "IPH_ReadingListInSidePanel",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHReadingModeSidePanelFeature,
             "IPH_ReadingModeSidePanel",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHShoppingCollectionFeature,
             "IPH_ShoppingCollectionFeature",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHSideSearchAutoTriggeringFeature,
             "IPH_SideSearchAutoTriggering",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHSideSearchFeature,
             "IPH_SideSearch",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHSideSearchPageActionLabelFeature,
             "IPH_SideSearchPageActionLabel",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHTabSearchFeature,
             "IPH_TabSearch",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHTrackingProtectionOffboardingFeature,
             "IPH_TrackingProtectionOffboarding",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHTrackingProtectionOnboardingFeature,
             "IPH_TrackingProtectionOnboarding",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHWebUITabStripFeature,
             "IPH_WebUITabStrip",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHDesktopSnoozeFeature,
             "IPH_DesktopSnoozeFeature",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHDesktopPwaInstallFeature,
             "IPH_DesktopPwaInstall",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHProfileSwitchFeature,
             "IPH_ProfileSwitch",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHWebUiHelpBubbleTestFeature,
             "IPH_WebUiHelpBubbleTest",
             base::FEATURE_DISABLED_BY_DEFAULT);
BASE_FEATURE(kIPHPriceTrackingInSidePanelFeature,
             "IPH_PriceTrackingInSidePanel",
             base::FEATURE_ENABLED_BY_DEFAULT);
BASE_FEATURE(kIPHBackNavigationMenuFeature,
             "IPH_BackNavigationMenu",
             base::FEATURE_DISABLED_BY_DEFAULT);
#endif  


}  // namespace feature_engagement
