// misesPrivate function
namespace misesPrivate {
  enum AppState {
    UNKNOWN,
    RUNNING,
    PAUSED,
    STOPPED,
    DESTROYED
  };
  callback GetInstallReferrerCallback = void(DOMString installReferrer);
  callback GetAppStateCallback = void(AppState state);
  interface Functions {
    // set mises id
    static void setMisesId(DOMString id);
    static void getInstallReferrer(GetInstallReferrerCallback callback);
    static void getAppState(GetAppStateCallback callback);
  };
};

