#ifndef MISES_CHROMIUM_SRC_EXTENSIONS_BROWSER_EXTENSION_FUNCTION_HISTOGRAM_VALUE_H_
#define MISES_CHROMIUM_SRC_EXTENSIONS_BROWSER_EXTENSION_FUNCTION_HISTOGRAM_VALUE_H_

// clang-format off
#define ENUM_BOUNDARY \
  MISESPRIVATE_START = 2000,\
  MISESPRIVATE_SETMISESID,\
  MISESPRIVATE_GETINSTALLREFERRER,\
  MISESPRIVATE_GETAPPSTATE,\
  MISESPRIVATE_NOTIFYPHISHINGDETECTED,\
  ENUM_BOUNDARY
// clang-format on

#include "src/extensions/browser/extension_function_histogram_value.h"

#undef ENUM_BOUNDARY

#endif  // MISES_CHROMIUM_SRC_EXTENSIONS_BROWSER_EXTENSION_FUNCTION_HISTOGRAM_VALUE_H_


