#ifndef MISES_IOS_CHROME_BROWSER_UI_POPUP_MENU_PUBLIC_POPUP_MENU_UI_UPDATING_H_
#define MISES_IOS_CHROME_BROWSER_UI_POPUP_MENU_PUBLIC_POPUP_MENU_UI_UPDATING_H_

#define PopupMenuTypeTabStripTabGrid \
  PopupMenuTypeMisesMenu,PopupMenuTypeWalletMenu,PopupMenuTypeTabStripTabGrid
#include "src/ios/chrome/browser/ui/popup_menu/public/popup_menu_ui_updating.h"
#undef PopupMenuTypeTabStripTabGrid
#endif
